@startuml

title 删除数据结点
autonumber

actor 企业管理员 as sysUser
boundary 统一门户 as loginWeb
boundary 企业云屏配置前端 as adminWeb
participant "数据节点服务\n<Service>" as nodeService
participant "数据资源服务\n<Service>" as resourceService
entity "数据节点" as nodes
entity "元数据" as metadata
entity "数据浏览器" as dataBrowser
participant 动态模型驱动 as data
participant 实体管理器 as beanmanager

activate sysUser
sysUser -> loginWeb: 请求登陆
activate loginWeb
return：登陆成功

sysUser -> adminWeb: 对象管理界面
activate adminWeb
return

sysUser -> adminWeb: 添加"主题管理"
activate adminWeb

adminWeb -> nodeService: 添加对象管理结点
activate nodeService

nodeService -> nodeService: 添加对象管理结点
activate nodeService #DarkSalmon

nodeService -> nodes: 保存数据结点
activate nodes
return：保存成功

nodeService -> metadata: 保存元数据
activate metadata
return：保存成功

nodeService -> dataBrowser: 保存数据浏览器
activate dataBrowser
return：保存成功

nodeService -> data: 创建动态模型
activate data
return：创建成功

nodeService -> beanmanager: 加载动态模型
activate beanmanager
return：加载成功

return
return

adminWeb -> adminWeb: 刷新页面，显示出新增的"主题管理"
return

sysUser -> adminWeb: 点击"主题管理"
activate adminWeb
adminWeb -> adminWeb: 显示"主题管理"界面
return

sysUser -> adminWeb: 录入并保存一个主题
activate adminWeb
adminWeb -> resourceService: 保存主题数据
activate resourceService
resourceService -> resourceService: 保存数据

return： 保存成功
return： 响应成功

@enduml