@startuml 可配置数据服务

DynamicModelRepository --|> SLAHelper
DynamicModelFactory --|> SLAHelper
ConfigRepositories --|> DynamicModelRepository
DataEntityRepositories --|> DynamicModelRepository
SLAHelper --|> DynamicModelRepository

@enduml