@startuml 可配置数据服务

class 数据结点 {
    结点标识
    结点名称
    元数据标识
    结点路径
    ==========
    保存结点(结点标识, 数据节点对象)
    更新单个结点的某个属性(结点标识, 属性名称，属性值)
    删除单个(结点标识)
    查询单个(结点标识)
    批量查询(查询条件)
}

class 元数据 {
    元数据标识
    元数据名称
    元数据内容
    ============
    保存元数据(元数据标识，元数据对象)
    删除单个(结点标识)
    查询单个(结点标识)
}

class 数据资源 {
    实体结点的标识
    结点路径
    数据资源的属性
    =================
    保存单个记录(结点路径标识, 数据对象)
    更新单个记录(结点标识)
    删除单个记录(结点标识)
    查询单个记录(结点标识)
    批量查询(结点标识，查询条件)
}

note left of 数据资源 
数据资源是根据元数据动态创建的
数据对象。数据资源的属性由结点
标识所关联的元数据的决定。
数据对象名为元数据的标识
end note

数据结点 "1" -right-> "1" 元数据: 单向关联
数据资源 ..> 元数据: 依赖
数据资源 ..> 数据结点: 依赖

note "’保存‘的含义是指，创建或者更新数据对象" as N1

@enduml